server:
  port: 8000

spring:
  devtools:
    livereload:
      # View 변경 실시간 적용
      enabled: true

  thymeleaf:
    # 뷰 경로 및 확장자 지정
    # 템플릿 캐싱 비활성화
    prefix: classpath:templates/
    suffix: .html
    cache: false

  h2:
    console:
      # H2 콘솔 활성화 및 웹 콘솔 주소
      enabled: true
      path: /console

  datasource:
    # H2 DB 접속 정보
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    # JPA 설정
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

  # i8n(Internationalization) 경로 및 인코딩 정보 지정
  # i18n 디렉터리의 error로 시작하는 파일 (_ko, _en 등 지역 언어별 파일 추가)
  messages:
    basename: i18n/error
    encoding: UTF-8

  jwt:
    secret: devsjh